name: tests
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - name: docker
      run: |
       
        # Installing requirements
        pip3 install -r requirements.txt

        # run the database in docker container
        docker compose up -d --build

        # verify that it is running successfully
        # this is an idempotent command useful for debugging
        echo "first docker" 
        docker ps -a


        sleep 20
      
        echo "second docker" 
        docker ps
        docker compose logs

        echo "web logs"
        docker compose logs web
       
        # load test data 
        # run test cases
        # Run insert test
        echo "Running insert test..."
        docker exec -u postgres final_website-db-1 \
        psql -U postgres -d postgres -f /test-sql/load_tweets.sql

        # Check exit status
        if [ $? -eq 0 ]; then
            echo "✅ Insert test passed"
        else
            echo "❌ Insert test failed"
            exit 1
        fi       
        # after the database starts successfully,
        # it needs time to load the pagila data;
        # this should happen in <1 second,
        # but we sleep for a long time just to be sure that everything is loaded;
        # this is a bit hacky,
        # and a proper check would be to have an infinite loop that terminates once the data has been loaded
        
        # run the tests
        #docker compose exec -T pg ./run_tests.sh

        # FIXME:
        # the docker-compose command above will generate an error when the github action is run
        # this is due to the `fixme.sh` file not existing
        # you will have to modify this file so that github actions runs the correct test cases
