name: tests
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Make script executable
      run: chmod +x ./load_tweets_parallel.sh

    - name: docker
      run: |
        # load the pagila data
        #git submodule init
        #git submodule update
        # Installing requirements
        pip3 install -r requirements.txt

        # run the database in docker container
        docker compose up -d --build

        # verify that it is running successfully
        # this is an idempotent command useful for debugging
        docker ps -a

        sleep 20
        # load test data 
        ./load_tweets_parallel.sh
        # run test cases
        
        # after the database starts successfully,
        # it needs time to load the pagila data;
        # this should happen in <1 second,
        # but we sleep for a long time just to be sure that everything is loaded;
        # this is a bit hacky,
        # and a proper check would be to have an infinite loop that terminates once the data has been loaded
        
        # run the tests
        #docker compose exec -T pg ./run_tests.sh

        # FIXME:
        # the docker-compose command above will generate an error when the github action is run
        # this is due to the `fixme.sh` file not existing
        # you will have to modify this file so that github actions runs the correct test cases
